name: mqtt_node
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  equatable: ^2.0.7
  uuid: ^4.4.0
  mqtt_client: ^10.5.1
  intl: ^0.20.2
  platform: ^3.1.0
  #path_provider: ^2.0.11

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
